[package]
name = "bookwormfood_types"
version = "0.1.0"
edition = "2021"
authors = ["rimutaka <max@onebro.me>"]
description = "Shared types and models for bookwormfood.com"
license = "GPL 3.0"

[dependencies]
wasm-bindgen = "0.2"
serde = { workspace = true }
chrono = { workspace = true }
